### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#201]
![image](https://user-images.githubusercontent.com/694831/73436415-c467cf80-434a-11ea-835b-79ea7b34f98d.png)

**Comment by ashygee** [comment]
Thanks to @simurai we found this example:

<img width="265" alt="Screenshot 2020-02-13 17 25 45" src="https://user-images.githubusercontent.com/10384315/74493085-e3577d00-4e85-11ea-87c1-f54e69266b91.png">
https://github.com/google/skia

It’s when a repo is “mirrored” instead of forked.

cc @colebemis @edokoa

**Comment by colebemis** [comment]
![image](https://user-images.githubusercontent.com/4608155/74506868-aef8b680-4eaf-11ea-9296-d00c2fe424a5.png)

☝️ These look a little too much like fold icons.

What about something like this?

<img width="16" alt="mirror" src="https://user-images.githubusercontent.com/4608155/74506811-7bb62780-4eaf-11ea-9a9a-6855d8d7ad2c.png">

<img width="296" alt="Screen Shot 2020-02-13 at 10 23 47 PM" src="https://user-images.githubusercontent.com/4608155/74506841-9092bb00-4eaf-11ea-8802-4830e5af4c65.png">

**Comment by edokoa** [comment]
Looks good!
