### ISSUE TITLE
File submodule

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#215]
![image](https://user-images.githubusercontent.com/694831/73439386-cf712e80-434f-11ea-9191-20257c104740.png)

**Comment by colebemis** [comment]
What about a folder with an arrow in it since a submodule basically means "this folder points to somewhere else"? I think this is a little less cluttered than the nested folder metaphor.

<img width="16" alt="file-submodule" src="https://user-images.githubusercontent.com/4608155/74489545-738fc500-4e7a-11ea-9d1f-8212a51ca190.png">


![image](https://user-images.githubusercontent.com/4608155/74489473-404d3600-4e7a-11ea-9798-a517c2c1ed7e.png)

**Comment by ashygee** [comment]
@colebemis thanks for explaining that! I think this metaphor works a lot better. 

@pmarsceill @jasonlong what do you think about this update?

**Comment by jasonlong** [comment]
Yeah if this icon is specifically for submodules, I think this metaphor works well since they're more like aliases or pointers than nested folders. :thumbsup:
