### ISSUE TITLE
24px - Symlink file

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#274]
This will affect / depend on two things:

* How we treat the bottom of file icons (this one makes cutting a little bit the bottom of the file more justified)
* How we treat the arrow

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A1717

![image](https://user-images.githubusercontent.com/694831/75152127-a5214f80-5708-11ea-90b3-872ba25daa2d.png)

**Comment by ashygee** [comment]
> How we treat the bottom of file icons (this one makes cutting a little bit the bottom of the file more justified)

@edokoa I thought we  had agreed already that the lower left corner would be where we treat file icon details the same. I think maybe I am misunderstanding the question though. 

I did make an iteration that brings the arrow up and in a little more
![image](https://user-images.githubusercontent.com/10384315/75216177-0288c100-5748-11ea-9b18-1c776a0e7255.png)
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=752%3A1933

> How we treat the arrow

For the 24px icons we should be using the line arrow instead of the triangle since there is space.


cc @colebemis

**Comment by edokoa** [comment]
I mean because @colebemis was testing making the bottom line shorter to mimic the rounded corner in other files vs. the straight line with rounded cap that matches the left vertical line. We can discuss it in the sync today.
